In [5]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
first_dataset = pd.read_csv('deliveries_updated_ipl_upto_2025.csv')
first_dataset.head(10)

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,...,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,18-04-2008,1
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
5,335982,1,0.6,0,6,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
6,335982,1,0.7,0,7,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,18-04-2008,1
7,335982,1,1.1,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,Z Khan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
8,335982,1,1.2,1,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,Z Khan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,4
9,335982,1,1.3,1,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,Z Khan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,4

In [7]:
second_dataset = pd.read_csv('matches_updated_ipl_upto_2025.csv')
second_dataset

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,...,team2,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,...,Kolkata Knight Riders,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,...,Chennai Super Kings,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,...,Rajasthan Royals,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,...,Deccan Chargers,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,...,Royal Challengers Bangalore,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,2025,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Indian Premier League,NaN,VK Sharma,Royal Challengers Bengaluru,2025-05-27,NaN,MA Gough,Lucknow,...,Royal Challengers Bengaluru,6,6.0,UV Gandhe,JM Sharma,P Dharmani,NaN,NaN,70.0,1473507
1165,2025,Maharaja Yadavindra Singh International Cricke...,Indian Premier League,NaN,VK Sharma,Royal Challengers Bengaluru,2025-05-29,NaN,MA Gough,New Chandigarh,...,Royal Challengers Bengaluru,6,8.0,R Pandit,Suyash Sharma,V Narayan Kutty,NaN,NaN,NaN,1473508
1166,2025,Maharaja Yadavindra Singh International Cricke...,Indian Premier League,20.0,UV Gandhe,Mumbai Indians,2025-05-30,NaN,R Pandit,New Chandigarh,...,Gujarat Titans,6,NaN,VK Sharma,RG Sharma,Prakash Bhatt,NaN,NaN,NaN,1473509
1167,2025,"Narendra Modi Stadium, Ahmedabad",Indian Premier League,NaN,Nitin Menon,Punjab Kings,2025-06-01,NaN,CB Gaffaney,Ahmedabad,...,Punjab Kings,6,5.0,KN Ananthapadmanabhan,SS Iyer,J Srinath,NaN,NaN,NaN,1473510
1168,2025,"Narendra Modi Stadium, Ahmedabad",Indian Premier League,6.0,Nitin Menon,Punjab Kings,2025-06-03,NaN,J Madanagopal,Ahmedabad,...,Punjab Kings,6,NaN,CB Gaffaney,KH Pandya,J Srinath,NaN,NaN,NaN,1473511

In [8]:
total_runs = first_dataset.groupby(['matchId','inning']).sum()['total_run'].add(1).reset_index()
total_runs

      matchId  inning  total_run
0      335982       1        223
1      335982       2         83
2      335983       1        241
3      335983       2        208
4      335984       1        130
...       ...     ...        ...
2360  1473510       2        208
2361  1473511       1        191
2362  1473511       2        185
2363  1485779       1        207
2364  1485779       2        209

[2365 rows x 3 columns]

In [9]:
#Selecting only first innings score to find target of each match
total_runs = total_runs[total_runs['inning']==1]

In [10]:
match_df = second_dataset.merge(total_runs[['matchId','total_run']],left_on='matchId',right_on='matchId')

In [11]:
match_df

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,...,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId,total_run
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,...,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982,223
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,...,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983,241
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,...,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984,130
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,...,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986,111
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,...,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985,166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,2025,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Indian Premier League,NaN,VK Sharma,Royal Challengers Bengaluru,2025-05-27,NaN,MA Gough,Lucknow,...,6,6.0,UV Gandhe,JM Sharma,P Dharmani,NaN,NaN,70.0,1473507,228
1165,2025,Maharaja Yadavindra Singh International Cricke...,Indian Premier League,NaN,VK Sharma,Royal Challengers Bengaluru,2025-05-29,NaN,MA Gough,New Chandigarh,...,6,8.0,R Pandit,Suyash Sharma,V Narayan Kutty,NaN,NaN,NaN,1473508,102
1166,2025,Maharaja Yadavindra Singh International Cricke...,Indian Premier League,20.0,UV Gandhe,Mumbai Indians,2025-05-30,NaN,R Pandit,New Chandigarh,...,6,NaN,VK Sharma,RG Sharma,Prakash Bhatt,NaN,NaN,NaN,1473509,229
1167,2025,"Narendra Modi Stadium, Ahmedabad",Indian Premier League,NaN,Nitin Menon,Punjab Kings,2025-06-01,NaN,CB Gaffaney,Ahmedabad,...,6,5.0,KN Ananthapadmanabhan,SS Iyer,J Srinath,NaN,NaN,NaN,1473510,204
1168,2025,"Narendra Modi Stadium, Ahmedabad",Indian Premier League,6.0,Nitin Menon,Punjab Kings,2025-06-03,NaN,J Madanagopal,Ahmedabad,...,6,NaN,CB Gaffaney,KH Pandya,J Srinath,NaN,NaN,NaN,1473511,191

In [12]:
match_df = match_df[["matchId","city","winner","total_run"]]

In [13]:
match_df

      matchId            city                       winner  total_run
0      335982       Bangalore        Kolkata Knight Riders        223
1      335983      Chandigarh          Chennai Super Kings        241
2      335984           Delhi             Delhi Daredevils        130
3      335986         Kolkata        Kolkata Knight Riders        111
4      335985          Mumbai  Royal Challengers Bangalore        166
...       ...             ...                          ...        ...
1164  1473507         Lucknow  Royal Challengers Bengaluru        228
1165  1473508  New Chandigarh  Royal Challengers Bengaluru        102
1166  1473509  New Chandigarh               Mumbai Indians        229
1167  1473510       Ahmedabad                 Punjab Kings        204
1168  1473511       Ahmedabad  Royal Challengers Bengaluru        191

[1169 rows x 4 columns]

In [14]:
match_df = match_df.rename(columns={"matchId" : "match_id"})

In [15]:
match_df = match_df.rename(columns={"total_run" : "total_runs"})

In [16]:
match_df

      match_id            city                       winner  total_runs
0       335982       Bangalore        Kolkata Knight Riders         223
1       335983      Chandigarh          Chennai Super Kings         241
2       335984           Delhi             Delhi Daredevils         130
3       335986         Kolkata        Kolkata Knight Riders         111
4       335985          Mumbai  Royal Challengers Bangalore         166
...        ...             ...                          ...         ...
1164   1473507         Lucknow  Royal Challengers Bengaluru         228
1165   1473508  New Chandigarh  Royal Challengers Bengaluru         102
1166   1473509  New Chandigarh               Mumbai Indians         229
1167   1473510       Ahmedabad                 Punjab Kings         204
1168   1473511       Ahmedabad  Royal Challengers Bengaluru         191

[1169 rows x 4 columns]

In [17]:
first_dataset = first_dataset.rename(columns={"matchId" : "match_id"})

In [18]:
second_dataset = first_dataset.rename(columns={"matchId" : "match_id"})

In [19]:
second_innings =  match_df.merge(first_dataset,on="match_id")
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run
0,335982,Bangalore,Kolkata Knight Riders,223,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,18-04-2008,1
1,335982,Bangalore,Kolkata Knight Riders,223,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
2,335982,Bangalore,Kolkata Knight Riders,223,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1
3,335982,Bangalore,Kolkata Knight Riders,223,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
4,335982,Bangalore,Kolkata Knight Riders,223,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278200,1473511,Ahmedabad,Royal Challengers Bengaluru,191,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-06-2025,0
278201,1473511,Ahmedabad,Royal Challengers Bengaluru,191,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-06-2025,6
278202,1473511,Ahmedabad,Royal Challengers Bengaluru,191,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-06-2025,4
278203,1473511,Ahmedabad,Royal Challengers Bengaluru,191,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-06-2025,6
278204,1473511,Ahmedabad,Royal Challengers Bengaluru,191,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-06-2025,6

In [20]:
second_innings = second_innings[second_innings['inning']==2]
second_innings.shape

(133903, 24)

In [21]:
second_innings['batting_team'].value_counts()

batting_team
Mumbai Indians                 15501
Kolkata Knight Riders          15423
Rajasthan Royals               14674
Chennai Super Kings            13550
Royal Challengers Bangalore    13426
Sunrisers Hyderabad            10770
Kings XI Punjab                10753
Delhi Daredevils               10027
Delhi Capitals                  6741
Gujarat Titans                  3948
Deccan Chargers                 3754
Punjab Kings                    3735
Lucknow Super Giants            3006
Pune Warriors                   2995
Gujarat Lions                   1832
Royal Challengers Bengaluru     1425
Rising Pune Supergiant           906
Rising Pune Supergiants          731
Kochi Tuskers Kerala             706
Name: count, dtype: int64

In [22]:
second_innings['batting_team'] = second_innings['batting_team'].replace('Delhi Daredevils','Delhi Capitals')
second_innings['bowling_team'] = second_innings['bowling_team'].replace('Delhi Daredevils','Delhi Capitals')

In [23]:
second_innings['batting_team'] = second_innings['batting_team'].replace('Deccan Chargers','Sunrisers Hyderabad')
second_innings['bowling_team'] = second_innings['bowling_team'].replace('Deccan Chargers','Sunrisers Hyderabad')

In [24]:
second_innings['batting_team'].value_counts()

batting_team
Delhi Capitals                 16768
Mumbai Indians                 15501
Kolkata Knight Riders          15423
Rajasthan Royals               14674
Sunrisers Hyderabad            14524
Chennai Super Kings            13550
Royal Challengers Bangalore    13426
Kings XI Punjab                10753
Gujarat Titans                  3948
Punjab Kings                    3735
Lucknow Super Giants            3006
Pune Warriors                   2995
Gujarat Lions                   1832
Royal Challengers Bengaluru     1425
Rising Pune Supergiant           906
Rising Pune Supergiants          731
Kochi Tuskers Kerala             706
Name: count, dtype: int64

In [25]:
second_innings['batting_team'] = second_innings['batting_team'].replace('Punjab Kings','Kings XI Punjab')
second_innings['bowling_team'] = second_innings['bowling_team'].replace('Punjab Kings','Kings XI Punjab')

In [26]:
second_innings['batting_team'].value_counts()

batting_team
Delhi Capitals                 16768
Mumbai Indians                 15501
Kolkata Knight Riders          15423
Rajasthan Royals               14674
Sunrisers Hyderabad            14524
Kings XI Punjab                14488
Chennai Super Kings            13550
Royal Challengers Bangalore    13426
Gujarat Titans                  3948
Lucknow Super Giants            3006
Pune Warriors                   2995
Gujarat Lions                   1832
Royal Challengers Bengaluru     1425
Rising Pune Supergiant           906
Rising Pune Supergiants          731
Kochi Tuskers Kerala             706
Name: count, dtype: int64

In [27]:
teams = ['Kolkata Knight Riders', 
         'Chennai Super Kings',
         'Kings XI Punjab', 
         'Rajasthan Royals',
         'Mumbai Indians',
         'Delhi Capitals',
         'Royal Challengers Bangalore',
         'Sunrisers Hyderabad',
        'Lucknow Super Giants',
         'Gujarat Titans']

In [28]:
second_innings = second_innings[second_innings['batting_team'].isin(teams)]
second_innings = second_innings[second_innings['bowling_team'].isin(teams)]

In [29]:
second_innings['bowling_team'].value_counts()

bowling_team
Mumbai Indians                 15720
Sunrisers Hyderabad            15484
Chennai Super Kings            15154
Kings XI Punjab                14476
Kolkata Knight Riders          13138
Royal Challengers Bangalore    12757
Delhi Capitals                 12487
Rajasthan Royals               11927
Lucknow Super Giants            3573
Gujarat Titans                  2880
Name: count, dtype: int64

In [30]:
second_innings['batting_team'].value_counts()

batting_team
Delhi Capitals                 15614
Kolkata Knight Riders          14480
Mumbai Indians                 14309
Rajasthan Royals               13889
Sunrisers Hyderabad            13618
Kings XI Punjab                13404
Chennai Super Kings            12816
Royal Challengers Bangalore    12620
Gujarat Titans                  3840
Lucknow Super Giants            3006
Name: count, dtype: int64

In [31]:
second_innings['current_Score'] = (
    second_innings
    .groupby('match_id')['total_run']
    .cumsum()
)
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,1
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,2
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0,2
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,3
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,194
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,200
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,200
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,1,201
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,207

In [32]:
#Simple maths to calculate runs left after each ball
second_innings['runs_left'] = second_innings['total_runs'] - second_innings['current_Score']
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,1,222
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,2,221
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,0,2,221
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,3,220
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,4,219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,194,10
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,200,4
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,200,4
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,1,201,3
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,207,-3

In [33]:
#Calculating ball left after each ball is thrown using unique formula
second_innings['balls_left'] = 120 - (second_innings['over'] * 6 + second_innings['ball'])
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,1,222,119
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,2,221,118
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,18-04-2008,0,2,221,117
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,3,220,116
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,NaN,18-04-2008,1,4,219,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,194,10,8
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,200,4,7
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,01-06-2025,0,200,4,6
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,01-06-2025,1,201,3,5
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,01-06-2025,6,207,-3,4

In [34]:
second_innings.dtypes

match_id              int64
city                    str
winner                  str
total_runs            int64
inning                int64
over_ball           float64
over                  int64
ball                  int64
batting_team            str
bowling_team            str
batsman                 str
non_striker             str
bowler                  str
batsman_runs          int64
extras                int64
isWide              float64
isNoBall            float64
Byes                float64
LegByes             float64
Penalty             float64
dismissal_kind          str
player_dismissed        str
date                    str
total_run             int64
current_Score         int64
runs_left             int64
balls_left            int64
dtype: object

In [35]:
second_innings['player_dismissed'] = second_innings['player_dismissed'].fillna("0")

In [36]:
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,1,222,119
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,2,221,118
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,0,2,221,117
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,3,220,116
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,4,219,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,0,01-06-2025,0,194,10,8
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,0,01-06-2025,6,200,4,7
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,0,01-06-2025,0,200,4,6
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,0,01-06-2025,1,201,3,5
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,NaN,0,01-06-2025,6,207,-3,4

In [37]:
second_innings['player_dismissed'] = second_innings['player_dismissed'].apply(lambda x:x if x=="0" else "1")

In [38]:
second_innings['player_dismissed'] = second_innings['player_dismissed'].astype('int')

In [74]:
wickets = (
    second_innings['player_dismissed']
    .notna()
    .groupby(second_innings['match_id'])
    .cumsum()
)

In [75]:
wickets = wickets.groupby(second_innings['match_id']).shift(fill_value=0)

In [76]:
second_innings['wickets_remaining'] = 10 - wickets

In [77]:
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left,wickets_remaining
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,1,222,119,10
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,2,221,118,9
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,0,2,221,117,8
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,3,220,116,7
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,4,219,115,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,0,01-06-2025,0,194,10,8,-103
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,0,01-06-2025,6,200,4,7,-104
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,0,01-06-2025,0,200,4,6,-105
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,0,01-06-2025,1,201,3,5,-106
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,NaN,0,01-06-2025,6,207,-3,4,-107

In [78]:
second_innings.drop('wickets_remaining', axis=1, inplace=True)

In [81]:
second_innings.head(10)

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,1,222,119
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,2,221,118
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,0,2,221,117
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,3,220,116
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,1,4,219,115
129,335982,Bangalore,Kolkata Knight Riders,223,2,0.6,0,6,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,0,4,219,114
130,335982,Bangalore,Kolkata Knight Riders,223,2,0.7,0,7,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,0,4,219,113
131,335982,Bangalore,Kolkata Knight Riders,223,2,1.1,1,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,bowled,1,18-04-2008,0,4,219,113
132,335982,Bangalore,Kolkata Knight Riders,223,2,1.2,1,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,NaN,0,18-04-2008,0,4,219,112
133,335982,Bangalore,Kolkata Knight Riders,223,2,1.3,1,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,4.0,NaN,NaN,0,18-04-2008,4,8,215,111

In [82]:
second_innings['player_dismissed'].dtype

dtype('int64')

In [85]:
wickets = second_innings.groupby('match_id')['player_dismissed'].cumsum()

In [86]:
second_innings['wickets_remaining'] = 10-wickets

In [88]:
second_innings.head(10)

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left,wickets_remaining
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,1,222,119,10
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,2,221,118,10
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,0,2,221,117,10
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,3,220,116,10
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,1,4,219,115,10
129,335982,Bangalore,Kolkata Knight Riders,223,2,0.6,0,6,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,0,4,219,114,10
130,335982,Bangalore,Kolkata Knight Riders,223,2,0.7,0,7,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,0,4,219,113,10
131,335982,Bangalore,Kolkata Knight Riders,223,2,1.1,1,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,bowled,1,18-04-2008,0,4,219,113,9
132,335982,Bangalore,Kolkata Knight Riders,223,2,1.2,1,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,NaN,0,18-04-2008,0,4,219,112,9
133,335982,Bangalore,Kolkata Knight Riders,223,2,1.3,1,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,4.0,NaN,NaN,0,18-04-2008,4,8,215,111,9

Current Run Rate

In [89]:
second_innings['crr'] = round((second_innings['current_Score']*6)/(120 - second_innings['balls_left']),2)
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,Penalty,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left,wickets_remaining,crr
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,0,18-04-2008,1,1,222,119,10,6.00
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,0,18-04-2008,1,2,221,118,10,6.00
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,0,18-04-2008,0,2,221,117,10,4.00
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,0,18-04-2008,1,3,220,116,10,4.50
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,NaN,0,18-04-2008,1,4,219,115,10,4.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,0,01-06-2025,0,194,10,8,5,10.39
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,0,01-06-2025,6,200,4,7,5,10.62
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,0,01-06-2025,0,200,4,6,5,10.53
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,0,01-06-2025,1,201,3,5,5,10.49
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,NaN,0,01-06-2025,6,207,-3,4,5,10.71

Required Run Rate

In [90]:
second_innings['rrr'] = round((second_innings['runs_left']*6)/(second_innings['balls_left']),2)
second_innings

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,dismissal_kind,player_dismissed,date,total_run,current_Score,runs_left,balls_left,wickets_remaining,crr,rrr
124,335982,Bangalore,Kolkata Knight Riders,223,2,0.1,0,1,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,0,18-04-2008,1,1,222,119,10,6.00,11.19
125,335982,Bangalore,Kolkata Knight Riders,223,2,0.2,0,2,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,0,18-04-2008,1,2,221,118,10,6.00,11.24
126,335982,Bangalore,Kolkata Knight Riders,223,2,0.3,0,3,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,0,18-04-2008,0,2,221,117,10,4.00,11.33
127,335982,Bangalore,Kolkata Knight Riders,223,2,0.4,0,4,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,0,18-04-2008,1,3,220,116,10,4.50,11.38
128,335982,Bangalore,Kolkata Knight Riders,223,2,0.5,0,5,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,0,18-04-2008,1,4,219,115,10,4.80,11.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277948,1473510,Ahmedabad,Punjab Kings,204,2,18.4,18,4,Kings XI Punjab,Mumbai Indians,...,NaN,0,01-06-2025,0,194,10,8,5,10.39,7.50
277949,1473510,Ahmedabad,Punjab Kings,204,2,18.5,18,5,Kings XI Punjab,Mumbai Indians,...,NaN,0,01-06-2025,6,200,4,7,5,10.62,3.43
277950,1473510,Ahmedabad,Punjab Kings,204,2,18.6,18,6,Kings XI Punjab,Mumbai Indians,...,NaN,0,01-06-2025,0,200,4,6,5,10.53,4.00
277951,1473510,Ahmedabad,Punjab Kings,204,2,18.7,18,7,Kings XI Punjab,Mumbai Indians,...,NaN,0,01-06-2025,1,201,3,5,5,10.49,3.60
277952,1473510,Ahmedabad,Punjab Kings,204,2,18.8,18,8,Kings XI Punjab,Mumbai Indians,...,NaN,0,01-06-2025,6,207,-3,4,5,10.71,-4.50

In [92]:
def winner(team):
    return 1 if team['batting_team'] == team['winner'] else 0

In [96]:
second_innings['results'] = second_innings.apply(winner,axis=1)
second_innings.sample()

,match_id,city,winner,total_runs,inning,over_ball,over,ball,batting_team,bowling_team,...,player_dismissed,date,total_run,current_Score,runs_left,balls_left,wickets_remaining,crr,rrr,results
69787,548355,Mumbai,Mumbai Indians,174,2,4.5,4,5,Mumbai Indians,Chennai Super Kings,...,0,06-05-2012,1,32,142,91,9,6.62,9.36,1

Only Taking required Data

In [105]:
required_data = second_innings[['batting_team','bowling_team','city','runs_left','balls_left','wickets_remaining','total_runs','crr','rrr','results']]
required_data

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_runs,crr,rrr,results
124,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,222,119,10,223,6.00,11.19,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,118,10,223,6.00,11.24,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,117,10,223,4.00,11.33,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,220,116,10,223,4.50,11.38,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,219,115,10,223,4.80,11.43,0
...,...,...,...,...,...,...,...,...,...,...
277948,Kings XI Punjab,Mumbai Indians,Ahmedabad,10,8,5,204,10.39,7.50,0
277949,Kings XI Punjab,Mumbai Indians,Ahmedabad,4,7,5,204,10.62,3.43,0
277950,Kings XI Punjab,Mumbai Indians,Ahmedabad,4,6,5,204,10.53,4.00,0
277951,Kings XI Punjab,Mumbai Indians,Ahmedabad,3,5,5,204,10.49,3.60,0
277952,Kings XI Punjab,Mumbai Indians,Ahmedabad,-3,4,5,204,10.71,-4.50,0

Sampling Data

In [106]:
final_data = required_data.sample(required_data.shape[0])

Dropping Null Values

In [107]:
final_data.dropna(inplace=True)

Removing rows where balls_left==0 to remove -inf and inf from rrr column

In [108]:
final_data = final_data[final_data['balls_left']!=0]

In [109]:
final_data.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_runs,crr,rrr,results
7930,Kings XI Punjab,Royal Challengers Bangalore,Chandigarh,127,103,10,144,6.0,7.4,1

Storing data in new csv

In [110]:
final_data.to_csv("final_data.csv", index=False)

Building Model

In [112]:
from sklearn.model_selection import train_test_split as tts

In [113]:
x = final_data.iloc[:, :-1]
y = final_data.iloc[:,-1]

In [114]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.25,random_state=100)
x_train

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_runs,crr,rrr
255445,Lucknow Super Giants,Mumbai Indians,Lucknow,76,68,8,145,7.96,6.71
128748,Kolkata Knight Riders,Delhi Capitals,Delhi,187,119,10,187,0.00,9.43
222449,Royal Challengers Bangalore,Kings XI Punjab,Mumbai,139,72,7,210,8.88,11.58
13653,Chennai Super Kings,Mumbai Indians,Cape Town,111,78,8,166,7.86,8.54
260189,Kolkata Knight Riders,Sunrisers Hyderabad,Ahmedabad,103,91,9,160,11.79,6.79
...,...,...,...,...,...,...,...,...,...
160598,Rajasthan Royals,Chennai Super Kings,Jaipur,123,91,8,177,11.17,8.11
152731,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata,51,48,7,139,7.33,6.38
274055,Gujarat Titans,Mumbai Indians,Mumbai,33,21,6,156,7.45,9.43
212885,Lucknow Super Giants,Rajasthan Royals,Mumbai,14,3,2,166,7.79,28.00
232966,Chennai Super Kings,Sunrisers Hyderabad,Chennai,62,69,10,135,8.59,5.39

In [115]:
x_test

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_runs,crr,rrr
62064,Kolkata Knight Riders,Rajasthan Royals,Kolkata,58,47,8,132,6.08,7.40
74140,Kings XI Punjab,Chennai Super Kings,Dharamsala,52,59,8,121,6.79,5.29
102325,Chennai Super Kings,Mumbai Indians,Mumbai,72,45,8,158,6.88,9.60
228065,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata,155,85,8,205,8.57,10.94
134542,Delhi Capitals,Sunrisers Hyderabad,Raipur,149,106,9,159,4.29,8.43
...,...,...,...,...,...,...,...,...,...
46703,Rajasthan Royals,Kings XI Punjab,Chandigarh,137,61,6,196,6.00,13.48
257145,Mumbai Indians,Sunrisers Hyderabad,Mumbai,80,53,7,174,8.42,9.06
260902,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,26,74,9,114,11.48,2.11
884,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,50,48,7,111,5.08,6.25
133492,Sunrisers Hyderabad,Kings XI Punjab,Chandigarh,121,79,10,180,8.63,9.19

In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'),
     ['batting_team','bowling_team','city'])
],
remainder='passthrough')

In [119]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [121]:
#Training Model
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [122]:
#Testing Model
y_pred = pipe.predict(x_test)

In [125]:
#Calculating Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7966619905758786

In [126]:
pipe.predict_proba(x_test)[0]

array([0.13543294, 0.86456706])

In [128]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [129]:
final_data['city'].unique()

<StringArray>
[     'Ahmedabad',        'Kolkata',          'Delhi',          'Dubai',
      'Bangalore',      'Hyderabad',           'Pune',    'Navi Mumbai',
      'Abu Dhabi',         'Mumbai',     'Chandigarh',        'Lucknow',
    'East London',      'Centurion',      'Cape Town',         'Jaipur',
         'Mohali',        'Chennai',        'Cuttack',  'Visakhapatnam',
     'Dharamsala',         'Raipur',         'Nagpur',   'Johannesburg',
         'Durban',         'Indore',         'Ranchi',        'Sharjah',
   'Bloemfontein',      'Bengaluru', 'New Chandigarh',       'Guwahati',
 'Port Elizabeth',      'Kimberley']
Length: 34, dtype: str

Random Forest classifier

In [132]:
from sklearn.ensemble import RandomForestClassifier
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
],
remainder='passthrough')

pipe = Pipeline([
    ('step1',trf),
    ('step2',RandomForestClassifier())
])

pipe.fit(x_train,y_train)

y_pred = pipe.predict(x_test)

accuracy_score(y_test,y_pred)

0.9976619546059494

In [135]:
pipe.predict_proba(x_test)[0]

array([0., 1.])

In [136]:
pickle.dump(pipe,open('pipe2.pkl','wb'))

In [137]:
final_data['batting_team'].unique()

<StringArray>
[             'Delhi Capitals',       'Kolkata Knight Riders',
 'Royal Challengers Bangalore',         'Sunrisers Hyderabad',
         'Chennai Super Kings',              'Mumbai Indians',
        'Lucknow Super Giants',            'Rajasthan Royals',
             'Kings XI Punjab',              'Gujarat Titans']
Length: 10, dtype: str

In [138]:
final_data['bowling_team'].unique()

<StringArray>
[             'Gujarat Titans',         'Sunrisers Hyderabad',
         'Chennai Super Kings',              'Mumbai Indians',
             'Kings XI Punjab',            'Rajasthan Royals',
       'Kolkata Knight Riders',              'Delhi Capitals',
 'Royal Challengers Bangalore',        'Lucknow Super Giants']
Length: 10, dtype: str